[variables]
NODE_VERSION = "20"
YARN_ENABLE_IMMUTABLE_INSTALLS = "true"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@3.2.3 --activate",
  "yarn --version",
  "yarn install --immutable --check-cache"
]

[phases.build]
cmds = []

[start]
cmd = "yarn start:railway"
