# See https://nixpacks.com/docs/configuration/file for schema
[variables]
NODE_VERSION = "18"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@3.2.3 --activate",
  "yarn install"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"
